export const UserInformationTeam = [
  {
    id: 1,
    accountNum: "20123",
    firstname: "Jon",
    lastname: "Snow",
    address: "Minglanilla",
    email: "jonsnow@gmail.com",
    designation: "BFP Naga City Fire Station",
    phone: "09569414023",
    group: "City Fire Marshal",
  },
  {
    id: 2,
    accountNum: "20124",
    firstname: "Cersei",
    lastname: "Lannister",
    address: "City of Naga",
    email: "cerseilannister@gmail.com",
    designation: "BFP Lapu-lapu City Fire District Station 3",
    phone: "09079291235",
    group: "Chief, FSES",
  },
  {
    id: 3,
    accountNum: "20125",
    firstname: "Jaime",
    lastname: "Lannister",
    address: "Talisay City",
    email: "jaimelannister@gmail.com",
    designation: "BFP Granada Sub Fire Station",
    phone: "09569214053",
    group: "City Fire Marshal",
  },
  {
    id: 4,
    accountNum: "20126",
    firstname: "Anya",
    lastname: "Stark",
    address: "Bulacao",
    email: "anyastark@gmail.com",
    designation: "Carcar City Fire Station",
    phone: "09569610333",
    group: "City Fire Marshal",
  },
  {
    id: 5,
    accountNum: "20127",
    firstname: "Daenerys",
    lastname: "Targaryen",
    address: "Mambaling",
    email: "daenerystargaryen@gmail.com",
    designation: "Boljoon Fire Station",
    phone: "09568218123",
    group: "Clerk",
  },
  {
    id: 6,
    accountNum: "20128",
    firstname: "Ever",
    lastname: "Melisandre",
    address: "Carcar",
    email: "evermelisandre@gmail.com",
    designation: "Mabolo Fire Sub Station",
    phone: "09910192315",
    group: "Clerk",
  },
  {
    id: 7,
    accountNum: "20129",
    firstname: "Ferrara",
    lastname: "Clifford",
    address: "Sibonga",
    email: "ferraraclifford@gmail.com",
    designation: "Lahug Fire Sub-Station",
    phone: "09910748206",
    group: "Clerk",
  },
  {
    id: 8,
    accountNum: "20130",
    firstname: "Rossini",
    lastname: "Frances",
    address: "Toledo City",
    email: "rossinifrances@gmail.com",
    designation: "Guadalupe Fire Station",
    phone: "09919190825",
    group: "Chief, FSES",
  },
  {
    id: 9,
    accountNum: "20131",
    firstname: "Harvey",
    lastname: "Roxie",
    address: "Santander",
    email: "harveyroxie@gmail.com",
    designation: "Pari-an Fire Sub Station",
    phone: "099385901654",
    group: "City Fire Marshal",
  },
  {
    id: 10,
    accountNum: "20132",
    firstname: "Manny",
    lastname: "Pacquiao",
    address: "Sarangani",
    email: "pacquiao123@gmail.com",
    designation: "BFP Tondo Fire Station",
    phone: "09918619102",
    group: "Building Plan Evaluator",
  },
  {
    id: 11,
    accountNum: "20133",
    firstname: "Kendrick",
    lastname: "Lamar",
    address: "California",
    email: "moneytrees@gmail.com",
    designation: "Santa Ana Fire Station",
    phone: "09919203012",
    group: "Encoder",
  },
  {
    id: 12,
    accountNum: "20134",
    firstname: "Snoop",
    lastname: "Dogg",
    address: "California",
    email: "snoop420@gmail.com",
    designation: "BFP Taguig City Fire Station 1",
    phone: "09919239613",
    group: "Building Plan Evaluator",
  },
  {
    id: 13,
    accountNum: "20135",
    firstname: "Rodrigo",
    lastname: "Duterte",
    address: "Davao",
    email: "tokhang@gmail.com",
    designation: "BFP Mariveles Fire Station",
    phone: "09912396915",
    group: "Encoder",
  },
  {
    id: 14,
    accountNum: "20136",
    firstname: "Hachi Drake",
    lastname: "Merto",
    address: "Minglanilla",
    email: "chuyens@gmail.com",
    designation: "Minglanilla Fire Station",
    phone: "09912385915",
    group: "Encoder",
  },
  {
    id: 15,
    accountNum: "20137",
    firstname: "Lowell",
    lastname: "Cambalon",
    address: "Punta",
    email: "longhair@gmail.com",
    designation: "BFP Punta Fire Station",
    phone: "09915136915",
    group: "Building Plan Evaluator",
  },
  {
    id: 16,
    accountNum: "20138",
    firstname: "Bernard",
    lastname: "del Rosario",
    address: "Day-as",
    email: "mrdj@gmail.com",
    designation: "BFP Day-as Fire Station",
    phone: "09915138913",
    group: "Building Plan Evaluator",
  },
  {
    id: 17,
    accountNum: "20139",
    firstname: "Kenneth",
    lastname: "Porras",
    address: "Labangon",
    email: "lods@gmail.com",
    designation: "BFP Labangon Fire Station",
    phone: "09913918513",
    group: "Chief, FSES",
  },
  {
    id: 18,
    accountNum: "20140",
    firstname: "Louella",
    lastname: "Tayco",
    address: "Punta",
    email: "taycoshi@gmail.com",
    designation: "BFP Labangon Fire Station",
    phone: "09916419113",
    group: "Clerk",
  },
];